USER openwrt
WORKDIR /home/openwrt
RUN git clone --quiet https://github.com/mirrors/openwrt.git
WORKDIR /home/openwrt/openwrt
RUN echo "CONFIG_TARGET_ar71xx=y" > .config
RUN make defconfig
RUN make prereq
RUN make tools
RUN make toolchain
